// Class automatically generated by Dev-C++ New Class wizard

#ifndef TOPRECORDE_H
#define TOPRECORDE_H

#include "RecordeManager.h"


#define ASSINATURA_JOGO_NOME 'R'+'e'+'g'+'R'+'e'+'c'+'o'+'r'+'d'+'e'
#define ASSINATURA_JOGO_SIGLA 'R'+'R'
#define ASSINATURA_JOGO_VERSAO 'v'+'0'+'1'


class TopRecorde
{
public:
	TopRecorde();
	~TopRecorde();
	bool adicionar(Recorde recorde);
	void imprimir();
	bool salvar();
	bool carregar();
	bool setRecordeManager(RecordeManager recordeManager);
	RecordeManager manager;	
protected:
	std::string arquivo;

private:
	const static int assCheckSize = 3;
	const static int assCheck[assCheckSize];

};

#endif // TOPRECORDE_H
